version: "3.9"

services:
  db:
    image: postgres:17
    container_name: mentor_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: mentor_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8081:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: mentor_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # tài khoản login pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin          # mật khẩu login pgAdmin
    ports:
      - "5050:80"   # mở pgAdmin ở http://localhost:5050
    depends_on:
      - db

volumes:
  pgdata:
